server:
  port: 5001
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://162.14.110.150:3306/compus_second?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: jh315322318.
    driver-class-name: com.mysql.cj.jdbc.Driver
  # jackson:
  #   property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  #   default-property-inclusion: ALWAYS
  #   time-zone: GMT+8
  #   date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB 
  redis:
    port: 6379
    host: 162.14.110.150

mybatis-plus:
  global-config:
    db-config:
      # logic-delete-field: delFlag
      # logic-delete-value: 1
      # logic-not-delete-value: 0
      # table-prefix: sg_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
